web/core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^test-404/$', 'core.views.error404'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/map/$', views.events_map, name='events_map'),
    url(r'^events/calendar.ics$', views.events_ical, name='icalendar'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^foundation/$', views.foundation, name='foundation'),
    url(r'^foundation/governing-document/$', views.governing_document,
        name='foundation-governing-document'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^2015/$', views.year_2015, name='year_2015'),
    url(r'^terms-conditions/$', views.terms_conditions, name='terms-conditions'),
    url(r'^privacy-cookies/$', views.privacy_cookies, name='privacy-cookies'),
    url(r'^workshop-box/$', views.workshop_box, name='workshop-box'),

    url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
    url(r'^sponsor-request/$', views.sponsor_request, name='sponsor-request'),
    url(r'^$', views.index, name='index'),
]

web/djangogirls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Admin link for password reset
    # See: https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/login.html#L61
    url(r'^admin/password_reset/$',
        RedirectView.as_view(url='/account/password_reset', permanent=True),
        name='admin_password_reset'),

    # Regular links:
    url(r'^community/', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'', include('applications.urls', namespace='applications')),
    url(r'', include('core.urls', namespace='core')),
]

web/core/forms.py
from captcha.fields import ReCaptchaField
from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from django.core.mail import send_mail
from django.template.loader import render_to_string
from slacker import Error as SlackerError

from core.models import ContactEmail, Event, User
from core.slack_client import user_invite


class BetterReCaptchaField(ReCaptchaField):
    """A ReCaptchaField that always works in DEBUG mode"""
    def clean(self, values):
        if settings.DEBUG:
            return values[0]
        return super(BetterReCaptchaField, self).clean(values)


class AddOrganizerForm(forms.Form):
    """
    Custom form for adding new organizers to an existing event.

    If user of given email already exists, they're added to the event and
    receive e-mail notification about it.

    If user is new, they're created (randomly generated password), invited
    to Slack and receive e-mail notification with instructions to login
    (including password).
    """
    event = forms.ModelChoiceField(queryset=Event.objects.all())
    name = forms.CharField(label="Organizer's first and last name")
    email = forms.CharField(label="E-mail address")

    def __init__(self, event_choices=None, *args, **kwargs):
        super(AddOrganizerForm, self).__init__(*args, **kwargs)
        if event_choices:
            self.fields['event'].queryset = event_choices

    def invite_to_slack(self, email, name):
        try:
            user_invite(email, name)
        except (ConnectionError, SlackerError) as e:
            self._errors.append('Slack invite unsuccessful, reason: {}'.format(e))

    def notify_existing_user(self, user):
        content = render_to_string('emails/existing_user.html', {
            'user': user,
            'event': self.cleaned_data['event']
        })
        subject = 'You have been granted access to new Django Girls event'
        self.send_email(content, subject, user)

    def notify_new_user(self, user):
        content = render_to_string('emails/new_user.html', {
            'user': user,
            'event': self.cleaned_data['event'],
            'password': self._password,
            'errors': self._errors,
        })
        subject = 'Access to Django Girls website'
        self.send_email(content, subject, user)

    def send_email(self, content, subject, user):
        send_mail(subject, content, "Django Girls <hello@djangogirls.org>",
                  [user.email])

    def save(self, *args, **kwargs):
        assert self.is_valid()
        self._errors = []
        email = self.cleaned_data['email']
        event = self.cleaned_data['event']

        user, created = User.objects.get_or_create(email=email)
        event.team.add(user)
        if created:
            self._password = User.objects.make_random_password()
            user.first_name = self.cleaned_data['name'].split(' ')[0]
            user.last_name = self.cleaned_data['name'].replace(user.first_name, '')
            user.is_staff = True
            user.is_active = True
            user.set_password(self._password)
            user.save()
            user.groups.add(1)
            self.invite_to_slack(email, user.first_name)
            self.notify_new_user(user)
        else:
            self.notify_existing_user(user)
        return user


class UserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification."
    )

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = auth_forms.ReadOnlyPasswordHashField(
        label="Password",
        help_text="Raw passwords are not stored, so there is no way to see "
                  "this user's password, but you can change the password "
                  "using <a href=\"password/\">this form</a>.")

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial["password"]


class UserLimitedChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')


class EventChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "{}, {}".format(obj.city, obj.country)


class ContactForm(forms.ModelForm):
    event = EventChoiceField(
        queryset=Event.objects.public().distinct('city', 'country').order_by('city'),
        required=False, label="Django Girls workshop in..."
    )
    captcha = BetterReCaptchaField()

    class Meta:
        model = ContactEmail
        fields = (
            'name',
            'email',
            'contact_type',
            'event',
            'message',
        )
        widgets = {'contact_type': forms.RadioSelect}

    def clean_event(self):
        contact_type = self.cleaned_data.get('contact_type')
        event = self.cleaned_data.get('event')
        if contact_type == ContactEmail.CHAPTER:
            if not event:
                raise forms.ValidationError('Please select the event')
        return event

web/core/views.py
import icalendar
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django_date_extensions.fields import ApproximateDate

from core.utils import next_deadline
# from patreonmanager.models import FundraisingStatus

from .forms import ContactForm
from .models import Event, EventPage, Story, User


def index(request):

    return render(request, 'core/index.html', {
        'future_events': Event.objects.future().select_related('eventpage'),
        'stories': Story.objects.filter(is_story=True).order_by('-created')[:2],
        'blogposts': Story.objects.filter(is_story=False).order_by('-created')[:3],
        # 'patreon_stats': FundraisingStatus.objects.all().first(),
        'organizers_count': User.objects.all().count(),
        'cities_count': Event.objects.values('city').distinct().count(),
        'country_count': Event.objects.values('country').distinct().count(),
    })


def events(request):

    return render(request, 'core/events.html', {
        'future_events': Event.objects.future().select_related('eventpage'),
        'past_events': Event.objects.past().select_related('eventpage'),
    })


def events_map(request):

    return render(request, 'core/events_map.html', {
        'events': Event.objects.public().order_by('date'),
        'mapbox_map_id': settings.MAPBOX_MAP_ID,
    })


def resources(request):
    return render(request, 'core/resources.html', {})


def organize(request):
    return render(request, 'core/organize.html', {})


def stories(request):

    return render(request, 'core/stories.html', {
        'stories': Story.objects.filter(is_story=True).order_by('-created'),
    })


def event(request, city):
    now = timezone.now()
    now_approx = ApproximateDate(year=now.year, month=now.month, day=now.day)
    page = get_object_or_404(
        EventPage.objects.select_related('event'),
        url=city.lower()
    )

    if page.url != city:
        return redirect('core:event', city=page.url, permanent=True)

    can_show = request.user.is_authenticated() or 'preview' in request.GET
    if not page.is_live and not can_show:
        return render(
            request,
            'applications/event_not_live.html',
            {'city': city, 'past': page.event.date <= now_approx}
        )

    return render(request, "core/event.html", {
        'page': page,
        'menu': page.menu.all(),
        'content': page.content.prefetch_related('coaches', 'sponsors').filter(is_public=True),
    })


def events_ical(request):
    events = Event.objects.public().order_by('-date')
    calendar = icalendar.Calendar()
    calendar['summary'] = "List of Django Girls events around the world"
    for event in events:
        ical_event = event.as_ical()
        if ical_event is None:
            continue  # Skip events with an approximate date
        calendar.add_component(ical_event)

    return HttpResponse(calendar.to_ical(),
                        content_type='text/calendar; charset=UTF-8')


def newsletter(request):
    return render(request, 'core/newsletter.html', {})


def faq(request):
    return render(request, 'core/faq.html', {})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact_email = form.save()
            if contact_email.sent_successfully:
                messages.add_message(
                    request,
                    messages.INFO,
                    "Thank you for your email. We will be in touch shortly."
                )
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    "Ooops. We couldn't send your email :( Please try again later"
                )
            return render(request, 'core/contact.html',
                          {'form': ContactForm()})
    else:
        form = ContactForm()
    return render(request, 'core/contact.html', {'form': form})


def foundation(request):
    return render(request, 'core/foundation.html', {})


def governing_document(request):
    return render(request, 'core/governing_document.html', {})


def contribute(request):
    return render(request, 'core/contribute.html', {})


def donate(request):
    return render(request, 'core/donate.html', {})


def year_2015(request):
    return render(request, 'core/2015.html', {
        'events': Event.objects.public().filter(date__lt='2016-01-01').order_by('date'),
        'mapbox_map_id': settings.MAPBOX_MAP_ID,
    })


def terms_conditions(request):
    return render(request, 'core/terms_conditions.html', {})


def privacy_cookies(request):
    return render(request, 'core/privacy_cookies.html', {})


def workshop_box(request):
    return render(request, 'core/workshop_box.html', {})

@login_required
def sponsor_request(request):
    return render(request, 'event/sponsor-request.html', {
        'deadline': next_deadline()
    })

web/templates/core/contact.html
{% extends 'global/base.html' %}
{% block title %}Django Girls Contact{% endblock %}

{% block content %}
    <div class="container without-background public-form" id="flatpage">
        <div id="value" class="row">
            <div class="col-md-12">
                <h2>Contact Django Girls</h2>

                {% include 'includes/_info_messages.html' %}

                <p>Hi! We would love to hear from you!</p>

                <p>To be sure your email reach the right person, check this FAQ first!</p>

                {% include 'includes/_faq.html' %}

                <p>
                    If you didn't find what you wanted, please check our extended <a href="{% url 'core:faq' %}">FAQ section</a> or use the form below. :)
                </p>

                <form action="" method="post" style="margin-top: 30px;">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6">
                          {% include 'includes/_field.html' with field=form.name %}
                        </div>
                        <div class="col-md-6">
                          {% include 'includes/_field.html' with field=form.email %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                          {% include 'includes/_field.html' with field=form.contact_type %}
                        </div>
                        <div class="col-md-6">
                          {% include 'includes/_field.html' with field=form.event %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                          {% include 'includes/_field.html' with field=form.message %}
                          {% include 'includes/_field.html' with field=form.captcha %}
                        </div>
                    </div>

                    <input type="submit" value="Send" />
                </form>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/core/contribute.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">

        <section id="resources">
            <div class="row clearfix">
                <div class="col-md-12">
                    <h2>Contribute</h2>
                    <p>
                        There are many ways to contribute to Django Girls: you can organize an event, coach, work on the tutorial and help on Gitter. If you'd rather help us financially, you can always support us on <a href="https://www.patreon.com/djangogirls">Patreon</a> or <a href="https://www.paypal.com/uk/webapps/mpp/search-cause?charityId=129929&s=3">Paypal Giving Funds</a>.
                    </p>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-6">
                    <h3>Support us!</h3>
                    <div class="cover">
                        <a href="https://www.patreon.com/djangogirls">
                            <img src="{% static 'img/global/contribute/love.jpg' %}" alt="Pixel heart and Django." />
                        </a>
                    </div>
                    <div class="info">

                        <p>Django Girls is a <a href="http://apps.charitycommission.gov.uk/Showcharity/RegisterOfCharities/CharityFramework.aspx?RegisteredCharityNumber=1163260&SubsidiaryNumber=0">Registered Charity</a> and is volunteer run. If you're an individual or a company and want to support us, you can make a <a href="https://www.patreon.com/djangogirls">monthly donation</a>. You can send one-time donations to our <a href="{% url 'core:donate' %}">PayPal account</a> or <a href="{% url 'core:donate' %}">donate via credit card</a>.</p>

                        <p>If you want to help an <a href="http://djangogirls.org/events">event</a> in particular, you can contact the local organization team to sponsor them.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3>Organize!</h3>
                    <div class="cover">
                        <a href="http://organize.djangogirls.org/">
                            <img src="{% static 'img/global/contribute/organize.jpg' %}" alt="Flowers and name tag on a table." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Each Django Girls event is a free, one-day workshop for 30-60 people on HTML, CSS, Python and Django. A typical workshop takes 8 hours and people work in small, 3-person groups with a coach dedicated to each group.</p>

                        <p>Want to get started? Check our <a href="http://organize.djangogirls.org/">Organizer's Manual</a> and <a href="https://djangogirls.org/organize/">bring Django Girls to your city!</a></p>
                    </div>
                </div>
            </div>

            <div class="row clearfix">
             <div class="col-md-6">
                    <h3>Coach!</h3>
                    <div class="cover">
                        <a href="http://djangogirls.org/events">
                            <img src="{% static 'img/global/contribute/coach.jpg' %}" alt="A coach helping an attendee." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Have you heard about an event happening in your city and you want to help? Contact the local <a href="http://djangogirls.org/events">organizing team</a> and ask if they need more coaches!</p>

                        <p>You will be helping a group of 3 people to install what they need for the event and guide them through our <a href="http://tutorial.djangogirls.org/">tutorial</a>.</p>

                        <p>Don't forget to check our <a href="http://coach.djangogirls.org/">Coaching Manual</a>!</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3>Work on the website!</h3>
                    <div class="cover">
                        <a href="https://github.com/DjangoGirls/djangogirls">
                            <img src="{% static 'img/global/contribute/debug.jpg' %}" alt="Computer screen with a console and a webpage." />
                        </a>
                    </div>
                    <div class="info">
                        <p>There is always something to do to make our website better. You can report (or fix!) bugs and typos, or work on new features.</p>

                        <p>We are waiting for your <a href="https://github.com/DjangoGirls/djangogirls">pull requests!</a></p>
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-6">
                    <h3>Fix the tutorial!</h3>
                    <div class="cover">
                        <a href="https://github.com/DjangoGirls/tutorial">
                            <img src="{% static 'img/global/contribute/tutoedit.jpg' %}" alt="A note book and a pen." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Is something in the tutorial not clear, or is there a typo? You can improve the tutorial by making a pull request to our <a href="https://github.com/DjangoGirls/tutorial">Github repository</a>.</p>

                        <p>You just finished our tutorial and want to help? Making pull requests to fix typo is a great way to use your new Git skills!</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3>Translate the tutorial!</h3>
                    <div class="cover">
                        <a href="https://crowdin.com/project/django-girls-tutorial">
                            <img src="{% static 'img/global/contribute/translate.jpg' %}" alt="A computer screen saying hello and golden balloons saying yay!." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Our tutorial has already been translated into <a href="http://tutorial.djangogirls.org/">8 languages</a>, but we always need helping maintaining those translations. Or you can help us translating the tutorial into a new language!</p>

                        <p>If you want to join an existing <a href="https://crowdin.com/project/django-girls-tutorial">translation team</a> or launch a new translation, <a href="mailto:translations@djangogirls.org">contact us</a>.</p>
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-6">
                    <h3>Help on Gitter!</h3>
                    <div class="cover">
                        <a href="https://gitter.im/DjangoGirls/tutorial">
                            <img src="{% static 'img/global/contribute/gitter.jpg' %}" alt="A web page opened on a computer." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Many people are doing our tutorial outside of a workshop. Sometimes, they get stuck and need help. How about spending a few hours a week helping them?</p>

                        <p>This <a href="https://gitter.im/DjangoGirls/tutorial">Gitter room </a> is designed to be a friendly space, especially for beginners. Remember that our <a href="https://djangogirls.org/pages/coc/">Code of Conduct</a> also applies there.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3>Want to do more?</h3>
                    <div class="cover">
                        <a href="https://trello.com/b/q7p6jcfg/django-girls">
                            <img src="{% static 'img/global/contribute/more.jpg' %}" alt="A pile a tattoo." />
                        </a>
                    </div>
                    <div class="info">
                        <p>Want to help out in a way that isn't listed here? You can look at our <a href="https://trello.com/b/q7p6jcfg/django-girls">Trello board</a> and propose new projects to work on.</p>

                        <p>Don't forget to read the rules described in the first column before adding a new card! ❤</p>
                    </div>
                </div>
            </div>
        </section>

    </div>

{% endblock %}

web/templates/core/donate.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
        <section>
            <div class="row clearfix">
                <div class="col-md-10 col-md-offset-1">
                    <h2>Donate to Django Girls</h2>
                    <p>
                      Django Girls is a volunteer run <a href="{% url 'core:foundation' %}">registered charity</a>. 
                      We use your generous donations to teach thousands women to build websites
                      using Python and Django annualy by providing resources and tools
                      to volunteer organizers all over the world.
                    </p>
                    <p>
                      We're transparent about our financials. See our <a href="{% url 'core:year_2015' %}">Annual Report for 2015</a>
                      to see how we spend donations and what impact they made.
                    </p>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-10 col-md-offset-1">
                    <h3>Donate monthly</h3>
                    If you would like to setup a small, recurring donation, we encourage you to do so via our 
                    <a href="https://www.patreon.com/djangogirls" target="_blank">Patreon page</a>.
                </div>
            </div>
            
            <div class="row clearfix">
                <div class="col-md-10 col-md-offset-1">
                    <h3>Donate via PayPal</h3>
                    If you would rather send us a gift through PayPal (either one-time, or recurringly),
                    you can do so by visiting <a href="https://www.paypal.com/uk/webapps/mpp/search-cause?charityId=129929&s=3" target="_blank">our PayPal Giving Fund page</a>.
                </div>
            </div>
            
            <div class="row clearfix">
                <div class="col-md-10 col-md-offset-1">
                    <h3>Donate by credit card</h3>
                    You can also send your donation by using a credit or debit card. Enter your details below, and 
                    your payment will be securely processed by DonorBox and Stripe:<br /><br />
                    
                    <script src="https://donorbox.org/widget.js" type="text/javascript"></script>
                    <iframe src="https://donorbox.org/embed/django-girls-foundation" height="685px" width="100%" style="max-width:500px; min-width:310px" seamless="seamless" id="dbox-form-embed" name="donorbox" frameborder="0" scrolling="no"></iframe>
                </div>
            </div>
        </section>

    </div>

{% endblock %}

web/templates/core/event.html
{% extends 'event/base.html' %}
{% load thumbnail %}

{% block title %}{{ page.title }}{% endblock %}
{% block description %}{{ page.description }}{% endblock %}
{% block custom_css %}
{% if page.custom_css %}
    <style>
        {{ page.custom_css }}
    </style>
{% endif %}
{% endblock %}

{% block content %}

    {% if messages or not page.is_live %}
    <div class="container messages">
        <div class="row">

            {% if not page.is_live%}
            <div class="alert alert-info" role="alert">Hi there! You can see this page because you're logged in admin. When you want to make it public, go to <a href="/admin/core/eventpage/{{ page.pk }}/change/">your website section in the admin</a> and click on 'Is live'.</div>
            {% endif %}

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}

    {% for item in content %}

        {% include 'includes/item.html' with item=item %}

    {% endfor %}

{% endblock %}

web/templates/core/events.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">

        <section id="events">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        Upcoming events
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:icalendar' %}">ICAL</a>
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:events_map' %}">MAP</a>
                    </h2>
                </div>
            </div>

            <div class="row">
                {% for event in future_events %}
                    {% include 'includes/_event.html' with event=event %}
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                {% endfor %}
            </div>

            <div class="row past-events">
                <div class="col-md-12">
                    <h2>Past events</h2>
                </div>
            </div>

            <div class="row">
                {% for event in past_events %}
                    {% include 'includes/_event.html' with event=event %}
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                {% endfor %}
            </div>

        </section>

        <section id="organize">
            {% include 'includes/_no_event.html' %}
        </section>

    </div>

{% endblock %}

web/templates/core/events_map.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <h2>Django Girls events</h2>
        <div id="map"></div>
    </div>
   
    <script>
        L.mapbox.accessToken = 'pk.eyJ1Ijoib2xhc2l0YXJza2EiLCJhIjoiZGUzZjUyNjUxYWNkOGU1ODBkYjcxNzc4MTllNGRlMjcifQ.t0yuSZmW5FvragLmVgJXNQ';
        var past = L.layerGroup()
        var future = L.layerGroup()
        var map = L.mapbox.map('map', '{{ mapbox_map_id }}', {scrollWheelZoom: false, layers: [past, future]}).setView([30, 0], 2);
        L.control.layers(null, {
          'Upcoming': future,
          'Past': past,
        }).addTo(map);

        {% for event in events %}
            {% if event.latlng %}
            L.marker([{{ event.latlng }}], {
                icon: L.mapbox.marker.icon({
                    'marker-size': 'medium',
                    'marker-symbol': 'heart',
                    'marker-color': '#{{ event.eventpage.main_color }}'
                })
              }).addTo(
                  {% if event.is_upcoming %}future{% else %}past{% endif %}
              ).bindPopup(
                  '{% if event.eventpage.is_live %}<a href="/{{ event.eventpage.url }}">{% endif %}{{ event.city }}, {{ event.country }}{% if event.eventpage.is_live %}</a>{% endif %}'
              );
            {% endif %}
        {% endfor %}
    </script>

{% endblock %}